question_filtering_task:
  description: >
    Answer the user's question on longevity based on the provided context.
  expected_output: >
    Question: {question}
    You are given a user input to the longevity question answering system.
    Please determine if the user's input message/question is relevant to longevity medicine. 
    Longevity medicine is a field of medicine that focuses on extending human lifespan and improving healthspan, covering topics accros aging, wellness, lifestyle, disease prevention, and personalised healthcare.
    Longevity interventions and treatments include: medications, repurposed drugs, supplements, lifestyle changes, exercise, nutrition, stress reduction, sleep optimisation, skincare, disease prevention, proactive healthcare, and more. 
    If the question is related to longevity, return "True". If it is completely unrelated, return "False".
  agent: question_filtering_agent
question_labelling_task:
  description: >
    Answer the user's question on longevity based on the provided context.
  expected_output: >
    Question: {question}
    You are given a user input to the longevity question answering system.
    If the question is not related to longevity medicine, provide no additional labels and skip the categorization.
    If the question is related to longevity medicine, label it according to the following categories:
    - "Supplements": Questions about supplements and/or vitamins 
    - "Disease": Questions about a specific disease or condition
    - "Nutrition": Questions about food, nutrition, and diet
    - "Exercise": Questions about exercise, fitness, and physical activity
    - "Sleep": Questions related to sleep
    Please provide a list of the labels most relevant to the question, separated by commas. 
    Please stick to the provided categories and do not modify them or create new ones. If the question does not fit any of these categories, return an empty list.
  agent: question_labelling_agent

