services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8023:8023"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./knowledge:/medai_flow/knowledge
      - ./input_data:/medai_flow/input_data
      - ./output_data:/medai_flow/output_data
      - ./logs:/medai_flow/logs
    restart: unless-stopped
    networks:
      - medai-network

  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - medai-network

networks:
  medai-network:
    driver: bridge

volumes:
  app-db-data:
